net br0
ip 10.10.20.2
whitelist /home/relia/relia-blocks
read-only /home/relia/relia-blocks
whitelist /home/relia/.gnuradio/prefs
read-only /home/relia/.gnuradio/prefs
whitelist /root/.gnuradio
read-only /root/.gnuradio
whitelist /tmp/relia-*
